apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: client
        image: wuxfsh/multi-client
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 3000

